# required
default_action = "SCMP_ACT_ALLOW"
# required, can be empty
extra_arch = ["x86"]

[[rules]]
# required
action = "SCMP_ACT_ERRNO"
# required
syscalls = [
    "bdflush",
    "io_pgetevents",
    "kexec_file_load",
    "kexec_load",
    "migrate_pages",
    "move_pages",
    "nfsservctl",
    "nice",
    "oldfstat",
    "oldlstat",
    "oldolduname",
    "oldstat",
    "olduname",
    "pciconfig_iobase",
    "pciconfig_read",
    "pciconfig_write",
    "sgetmask",
    "ssetmask",
    "swapcontext",
    "swapoff",
    "swapon",
    "sysfs",
    "uselib",
    "userfaultfd",
    "ustat",
    "vm86",
    "vm86old",
    "vmsplice",
    "bpf",
    "fanotify_init",
    "lookup_dcookie",
    "perf_event_open",
    "quotactl",
    "setdomainname",
    "sethostname",
    # Required Chromium and electron apps
    # "chroot",
    "delete_module",
    "init_module",
    "finit_module",
    "query_module",
    "acct",
    "iopl",
    "ioperm",
    "settimeofday",
    "stime",
    "clock_settime",
    "clock_settime64",
    "vhangup",
]

# Extra flags from firejail profiles
[[rules]]
action = "SCMP_ACT_ERRNO"
syscalls = [
    "ptrace",
    # Steam crash without these syscalls
    # "mount",
    # "umount2",
    "process_vm_readv",
    "open_by_handle_at",
]
